# External validation against reported ideology

This notebook asks how well DYNAMAP coordinates predict reported left–right identification. It fits four random-forest specifications on the **same participants and the same ten folds** in each country: coordinates, demographics, both together, and the first principal component of the coordinates.

**Inputs:** supplied participant coordinates in `outputs/models/`, original metadata in `data/raw/`, age decisions in `data/processed/`, and participant comparison counts. Notebooks 01–03 regenerate those inputs. You can run this notebook in a fresh kernel without running those notebooks first because their outputs are included.

**Outputs:** participant samples, out-of-fold predictions, fold metrics, ROC data, feature importances, and activity-group summaries in `outputs/validation/`. Notebooks 15 and 16 use these files for figures and tables.

Run all cells to refit the external classifiers. This fits 120 forests of 2,000 trees, so allow time for the analysis to finish. The random-forest, cross-validation and activity-bin settings are visible below. Changing them regenerates the validation outputs, but does not retrain DYNAMAP.

Labels are used only as external outcomes. Chilean positions 0–4 are left and 6–10 are right. French and Brazilian positions 1–2 are left and 4–5 are right. Central and nonresponse categories are omitted from this binary comparison.

People with unknown ages remain in the DYNAMAP maps. For this four-way comparison, however, all demographic predictors must be available: a known age of 19–120 in Chile or an age-category code of 2–7 in France and Brazil, plus the sex and region rules below. This restriction gives all four classifiers an identical evaluation sample.

In [1]:
from pathlib import Path
import json
import time

import numpy as np
import pandas as pd
from IPython.display import display
from sklearn.decomposition import PCA
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    recall_score,
    roc_auc_score,
    roc_curve,
    confusion_matrix,
)
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import MinMaxScaler

ROOT = Path.cwd()
if ROOT.name == "notebooks":
    ROOT = ROOT.parent
assert (ROOT / "data/raw").is_dir(), "Open from the project root or notebooks directory."

OUT = ROOT / "outputs/validation"
OUT.mkdir(parents=True, exist_ok=True)
COUNTRIES = ["Chile", "France", "Brazil"]
COORDINATES = {
    "Chile": "outputs/models/Chile_dim2_seed101/coordsU.csv",
    "France": "outputs/models/france/coordsU.csv",
    "Brazil": "outputs/models/brazil/coordsU.csv",
}
COUNTS = {
    "Chile": "data/processed/Chile_participant_support.csv",
    "France": "outputs/tables/france_participation_counts.csv",
    "Brazil": "outputs/tables/brazil_participation_counts.csv",
}
RF_PARAMETERS = {"n_estimators": 2000, "criterion": "entropy", "random_state": 42, "n_jobs": 2}
CV_PARAMETERS = {"n_splits": 10, "shuffle": True, "random_state": 42}
ACTIVITY_GROUPS = 10
DEMOGRAPHICS = {
    "Chile": ["age", "sex", "region"],
    "France": ["age", "sex"],
    "Brazil": ["age", "sex", "region"],
}

age_decisions = pd.read_csv(
    ROOT / "data/processed/participant_age_decisions.csv", dtype={"uuid": str}
)
assert not age_decisions.duplicated(["country", "uuid"]).any()
assert age_decisions.include.isin([True, False]).all()

# Match the original demographic coding, including alternate region spellings.
CHILE_REGION = {
    0: 0,
    "Arica y Parinacota": 1,
    "Tarapacá": 2,
    "Antofagasta": 3,
    "Atacama": 4,
    "Coquimbo": 5,
    "Valparaíso": 6,
    "Metropolitana de Santiago": 7,
    "Santiago Metropolitan": 7,
    "O'Higgins": 8,
    "Maule": 9,
    "Ñuble": 10,
    "Biobío": 11,
    "Biobio": 11,
    "Araucanía": 12,
    "Los Ríos": 13,
    "Los Lagos": 14,
    "Aysén": 15,
    "Magallanes": 16,
    "Outside of Chile": 17,
    "Fuera de Chile": 17,
}

BRAZIL_REGION = {
    "PR": 0,
    "RS": 1,
    "MG": 2,
    "PE": 3,
    "GO": 4,
    "SC": 5,
    "AC": 6,
    "MS": 7,
    "PB": 8,
    "AL": 9,
    "BA": 10,
    "RJ": 11,
    "SP": 12,
    "DF": 13,
    "SE": 14,
    "ES": 15,
    "RN": 16,
    "RO": 17,
    "CE": 18,
    "AM": 19,
    "RR": 20,
    "MA": 21,
    "PA": 22,
    "PI": 23,
}

## Build one unambiguous record per participant

The metadata join can contain multiple survey rows for a participant. Exact duplicates are harmless and are removed. If rows disagree on a predictor or the binary outcome, the entire ID is excluded rather than choosing one response. Missing or uncodable predictors also exclude the ID from this common validation sample. The exclusions and retained class counts are displayed below.

France uses `(z2, 1-z1)` to retain the original classifier column convention. This is a rigid rotation and translation: it changes neither Euclidean distances nor the information in the two coordinates. It uses no ideological labels and does not align independently fitted countries.

In [2]:
frames = {}
sample_rows = []
for country in COUNTRIES:
    destination = OUT / country
    destination.mkdir(parents=True, exist_ok=True)
    key = "uuid" if country == "Chile" else "user_id"
    metadata_path = ROOT / "data" / "raw" / f"{country.lower()}_metadata.csv"
    coordinate_path = ROOT / COORDINATES[country]
    metadata = pd.read_csv(metadata_path, dtype={key: str})
    coordinates = pd.read_csv(coordinate_path, dtype={key: str})
    assert coordinates[key].is_unique
    decisions = age_decisions[
        age_decisions.country.str.casefold() == country.casefold()
    ].set_index("uuid")
    assert set(coordinates[key]).issubset(decisions.index)
    assert decisions.loc[coordinates[key], "include"].all()
    # Each metadata row must match one coordinate row. Repeated survey rows are handled below.
    frame = pd.merge(metadata, coordinates, on=key, validate="many_to_one")
    left = [0, 1, 2, 3, 4] if country == "Chile" else [1, 2]
    right = [6, 7, 8, 9, 10] if country == "Chile" else [4, 5]
    frame = frame[frame.politica.isin(left + right)].copy()
    frame["target"] = frame.politica.isin(right).astype(int)
    demo = DEMOGRAPHICS[country]
    columns = demo + ["z1", "z2"]
    original_ids = frame[key].nunique()
    frame = frame[[key] + columns + ["target"]].drop_duplicates().copy()
    # Exclude ambiguous IDs before recoding to avoid selecting an arbitrary response.
    reasons = {}
    for identifier, group in frame.groupby(key, sort=False):
        differing = [
            col for col in columns + ["target"] if group[col].nunique(dropna=False) > 1
        ]
        missing = [col for col in columns + ["target"] if group[col].isna().any()]
        if differing or missing:
            reasons[identifier] = {"conflicting_fields": differing, "missing_fields": missing}
    clean = frame[~frame[key].isin(reasons)].copy()
    if country == "Chile":
        clean["sex"] = clean.sex.map({"Femenino": 0, "Masculino": 1, "Otro": 2})
        clean["region"] = clean.region.map(CHILE_REGION)
    elif country == "Brazil":
        clean["region"] = clean.region.map(BRAZIL_REGION)
    else:
        old_z1 = clean.z1.copy()
        clean["z1"] = clean.z2
        clean["z2"] = 1 - old_z1
    for col in columns:
        clean[col] = pd.to_numeric(clean[col], errors="coerce")
    # Coercion marks unknown region labels and nonnumeric predictors as missing.
    invalid = ~np.isfinite(clean[columns].to_numpy()).all(axis=1)
    for identifier in clean.loc[invalid, key]:
        reasons[identifier] = {
            "conflicting_fields": [],
            "missing_fields": ["uncodable_or_nonfinite_predictor"],
        }
    clean = clean.loc[~invalid].copy()
    # Unknown ages are valid for mapping, but cannot be demographic predictors here.
    eligibility_reasons = {}
    for _, row in clean.iterrows():
        fields = []
        if country == "Chile":
            if not 19 <= row.age <= 120:
                fields.append("known_age_required_19_120")
        else:
            if row.age not in range(2, 8):
                fields.append("known_age_required_codes_2_7")
            if row.sex not in [1, 2]:
                fields.append("sex_not_in_codes_1_2")
        if fields:
            eligibility_reasons[row[key]] = fields
            reasons[row[key]] = {
                "conflicting_fields": [],
                "missing_fields": [],
                "eligibility_fields": fields,
            }
    clean = clean[~clean[key].isin(eligibility_reasons)].copy()
    assert clean[key].is_unique
    clean = clean.rename(columns={key: "participant_id"}).reset_index(drop=True)
    assert clean.target.value_counts().min() >= CV_PARAMETERS["n_splits"]
    assert clean.participant_id.isin(coordinates[key]).all()
    display(clean)
    clean.to_csv(destination / "eligible_participants.csv", index=False)
    frames[country] = clean
    exclusion_table = pd.DataFrame(
        [
            {
                "participant_id": identifier,
                "conflicting_fields": ";".join(reason["conflicting_fields"]),
                "missing_fields": ";".join(reason["missing_fields"]),
                "eligibility_fields": ";".join(reason.get("eligibility_fields", [])),
            }
            for identifier, reason in reasons.items()
        ],
        columns=[
            "participant_id",
            "conflicting_fields",
            "missing_fields",
            "eligibility_fields",
        ],
    )
    display(exclusion_table)
    exclusion_table.to_csv(destination / "exclusions.csv", index=False)
    sample_rows.append(
        {
            "country": country,
            "map_participants": len(coordinates),
            "binary_label_ids_before_cleaning": int(original_ids),
            "excluded_from_common_sample": len(reasons),
            "common_sample": len(clean),
            "left": int(clean.target.eq(0).sum()),
            "right": int(clean.target.eq(1).sum()),
        }
    )

sample_summary = pd.DataFrame(sample_rows)
display(sample_summary)
sample_summary.to_csv(OUT / "validation_sample_audit.csv", index=False)
sample_summary.to_latex(OUT / "validation_sample_audit.tex", index=False)

,participant_id,age,sex,region,z1,z2,target
0,8bd42737-b140-4db8-af4c-59839922129a,27,1,11,0.277013,0.199440,0
1,7d2e034a-3270-4429-aeac-418c46bf0d7d,43,1,7,0.364785,0.264025,1
2,c1b97bb6-03d2-4027-8d54-0dd64a927a6c,39,0,7,0.490336,0.318748,0
3,883528e9-0599-4d30-9f4c-1daf9cf74082,34,1,7,0.429439,0.882237,1
4,7fd1210c-b1c0-4bdf-b190-7bfa10fe51d2,41,1,17,0.179798,0.743944,0
...,...,...,...,...,...,...,...
22019,759b16f2-f527-4f04-85ba-682fd1af8a89,41,1,9,0.177947,0.396998,0
22020,2e8f5550-d794-411c-b36e-d277e88f5d30,33,0,9,0.590559,0.113771,1
22021,3ddc9eae-ba7b-4dab-8e43-5c188daf9692,51,0,14,0.424433,0.334131,0
22022,b7132b2c-5ca4-44ac-b4e7-07e43d4b7547,33,1,7,0.473798,0.253386,1
22023,1a38e668-bad8-41e5-9e24-050480272131,59,1,8,0.172899,0.232025,0

,participant_id,conflicting_fields,missing_fields,eligibility_fields
0,d58cde44-5aa9-416f-9f1e-1f2841fac4b1,region,,
1,fc25f6e6-2351-499c-a3a4-3ab09694a869,target,,
2,1bdee467-b056-45dc-8c1d-6c47b591c89c,target,,
3,e012760e-08a4-47a6-bbf3-57a118c68925,target,,
4,87a5517a-f670-48d1-9850-bd7c4fde4025,sex,,
5,c5823f53-1b0c-4ad7-b804-50702fe37d6b,region,,
6,bcf58bd5-c7b3-4c86-87c2-bf36d3f5a29f,sex,,
7,d814cc9e-76e2-4ff1-86e9-0159601e6929,target,,
8,9ea04235-600d-4907-a6ba-b01e2ee1b501,target,,
9,84bb8768-cede-44cc-9b37-c59601ad430c,target,,
10,3426c241-fed5-4acb-a492-3162d6e24685,region,,
11,59a4ff59-114d-4c79-815e-8fae385be646,target,,
12,b947e142-d867-4d54-809f-b4248367c897,target,,
13,e3acad40-0114-4959-b023-d5e7d084774f,target,,
14,af8404e9-825d-497d-90ae-d7c78b2e53bc,target,,
15,a4b8e6aa-c4ab-41f4-a512-85f8018188cd,sex,,
16,5dd947b0-d656-47d5-acd8-228aac6a3e41,target,,
17,f54739ab-f9c9-4987-bb50-2ac53394e0e4,target,,
18,65a843ac-cdc7-46c0-a34a-85e81997e878,sex,,
19,19c31935-99c6-40a7-aac1-4034e0238157,region,,
20,4b0b02d3-af8f-4f26-a6f9-7713d46d0e23,target,,
21,a0be15cf-7916-4087-bb88-c3fce6b0bcad,target,,
22,9645b190-7dad-4817-9808-b558f5441a4d,target,,
23,8133049b-35c4-48db-943a-042daefcb4e6,target,,
24,a773ab8c-e776-443f-bce9-77c62f21c669,sex,,
25,a93755da-7717-4c20-814c-a948f11d8d92,target,,
26,68b0c1da-f12d-4c52-a0a8-8a5d8e7a4804,sex,,
27,34769db1-9d8a-4dc7-9b22-a806c810f03e,target,,
28,df0ce575-63b2-4956-89be-0fd7d109532e,sex;target,,
29,5b246b2a-c2ca-4f9e-9f56-d283692aa3da,target,,
30,5bf8fc87-0967-4e22-936a-7e5d4af683fd,region,,
31,7bb4dbc0-492a-435f-b6c7-e090ea3e785c,region,,
32,1781ae79-cc01-416a-8437-cda5501cd59d,target,,
33,36cae40d-5361-4e49-bd2e-f177c2716458,region,,
34,9e9ea8b9-4df2-4045-b652-3a9be6b00fb5,target,,
35,e1b7cc48-3f5b-45d3-8fe1-0afdcf17ff64,sex,,
36,2a5b45e9-db43-4d92-bfa6-e471f95d8fe1,target,,
37,6f53593e-cc8a-4779-accc-a10f37d6a1de,target,,
38,f429e06c-3343-49d6-94a1-c4f7fe0c7b95,target,,
39,a7e55b26-7783-4430-961f-c78f972efb5e,target,,
40,68fc6d52-6543-49a6-869c-544edd87e84a,sex,,
41,ffb2d999-093a-4a3d-9c93-06aaa1b8c755,region,,
42,f7865111-3fd5-4198-bb8e-933692fd1572,region,,
43,d6e5216b-1fce-4f92-a7b9-f1f9ed2da9d1,target,,
44,18104105-f9e5-479a-a509-42285e67b9dc,target,,
45,86fbeee2-cea3-4799-8dad-516105aeccd8,region,,
46,4263ef77-c91a-4153-b458-9f0073d51068,sex,,

,participant_id,age,sex,z1,z2,target
0,e9001e65-7aa1-468d-a7c6-dca4ad023e59,2,1,6.933758e-02,0.374006,0
1,41e3bf3a-e792-4521-8d3a-8f974f329345,2,1,1.806362e-04,0.299299,0
2,a664ff56-e303-4ab5-8841-bc950222e75f,3,1,1.541898e-07,0.246321,0
3,7490cb32-18ba-4572-9310-c0c3801438d0,2,2,7.282050e-01,0.502114,1
4,fecf3440-84f3-4bcb-b2c4-f6c939d80ec7,2,1,1.193472e-04,0.327659,0
...,...,...,...,...,...,...
783,9026410e-9aa7-4bf8-aafa-8dbd26c94c63,2,2,7.172434e-01,0.456519,1
784,67e9a740-4137-4834-9331-a54929c5e6a9,5,1,1.640098e-01,0.244334,0
785,48243d8e-ab20-4379-b9ba-ba76c4cde2f3,3,1,2.499202e-01,0.386546,0
786,a7adb7e7-e526-49b9-93d5-563f75aa7714,2,2,3.109551e-03,0.205531,0
787,23dc2d73-ff4b-4b6b-b4fb-35380d616e18,2,2,4.661192e-01,0.329383,0

,participant_id,conflicting_fields,missing_fields,eligibility_fields
0,118fed35-ddfd-402d-888b-88bb3bffdbd0,sex,,
1,539b2141-4d8a-4ff0-890a-beac65df93b7,,,sex_not_in_codes_1_2
2,e5db20f0-0bc8-493e-85da-dfadf9e41421,,,sex_not_in_codes_1_2
3,a1653595-b08e-4ad0-927f-8c94f094019a,,,sex_not_in_codes_1_2
4,2c1c9180-6a55-47b9-b563-96ce2538bcbc,,,sex_not_in_codes_1_2
5,4ec52ca2-1fdb-48e9-8861-4f8306984c65,,,sex_not_in_codes_1_2
6,d16fbdf2-4618-406d-85f1-057acebce618,,,sex_not_in_codes_1_2
7,8a65e0a0-c707-4531-8db2-58f577d58685,,,sex_not_in_codes_1_2
8,7df72060-aa57-4c1d-bec7-8990861dea0f,,,sex_not_in_codes_1_2
9,9890b3cd-8e4a-4764-bcdb-271299fdc060,,,known_age_required_codes_2_7;sex_not_in_codes_1_2
10,499da591-7e27-4635-bd20-25d2050562b9,,,sex_not_in_codes_1_2
11,22bdaf20-5a79-4f4c-b7c4-844165a38628,,,sex_not_in_codes_1_2
12,a6ae6a48-7359-460e-87c3-16baa605056a,,,sex_not_in_codes_1_2
13,f07f5619-1b18-4010-8374-e9db9b11ff55,,,sex_not_in_codes_1_2
14,96e5de4f-dd12-42a7-a588-ac03bb419811,,,sex_not_in_codes_1_2
15,0a6ef30e-74a3-4a6d-9f25-871bc8f2c6d5,,,sex_not_in_codes_1_2
16,73431c02-18ac-4d3c-ab87-127a66d88256,,,sex_not_in_codes_1_2
17,b7323948-9998-430a-9d42-d908785a3782,,,sex_not_in_codes_1_2
18,b8a8c9b8-13d4-4872-94c7-24fc1c31e357,,,sex_not_in_codes_1_2
19,f3d45e3a-0e16-4f00-a00e-abcc5952af38,,,sex_not_in_codes_1_2
20,7cf3b0f5-d13f-4314-93b2-b170c3223fb1,,,sex_not_in_codes_1_2
21,cbe2a561-a2b5-4f17-a2f4-2f9ed85a2239,,,sex_not_in_codes_1_2
22,dc450273-ecd5-4469-ba91-c7153ac86ab2,,,sex_not_in_codes_1_2
23,2ad39aef-2ce1-4f84-ac90-f6c934145c88,,,sex_not_in_codes_1_2
24,e527fec9-caf2-488f-b85f-6dd25d728bd0,,,sex_not_in_codes_1_2

,participant_id,age,sex,region,z1,z2,target
0,e3428c81-c1a3-4139-9deb-ab2b9aae481d,4,2,1,0.666261,0.503207,0
1,248860f8-a008-4207-84fd-a88cdc02e3f1,5,2,1,0.468704,0.514399,0
2,f3d2061a-9ffa-4fc2-bf46-f9990b6055ec,3,1,1,0.648949,0.380455,0
3,457cc0fc-957a-4984-a685-587b0686d18d,4,2,1,0.847903,0.614312,0
4,fc8481a9-7975-43f3-8a76-c054d51e73ea,3,1,1,0.335343,0.527585,1
...,...,...,...,...,...,...,...
490,33c490b5-f5e4-4db9-8d77-4f76fd0d363f,2,2,18,0.509419,0.426989,0
491,5d5f537f-a895-49ed-966d-a5b31539155d,5,1,12,0.277823,0.535905,1
492,035fef84-952f-40cf-b6bc-59419ebc4234,6,1,12,0.329012,0.429228,1
493,730666d4-bf22-4c25-9df0-cd447cd72100,6,2,4,0.360268,0.407338,1
494,464341cf-d0ec-4067-8905-a50b34a7fd90,4,2,2,0.403744,0.499950,1

,participant_id,conflicting_fields,missing_fields,eligibility_fields
0,adac3794-d0c1-4303-ab1b-aa79aec47a0b,,,sex_not_in_codes_1_2
1,0795ecd3-c623-464d-be92-f969664a6e11,,,sex_not_in_codes_1_2
2,3ba8a75e-1711-4c96-8c9b-7888e70fcdca,,,sex_not_in_codes_1_2
3,97752f8e-da1b-4963-b44f-b31c68635dda,,,sex_not_in_codes_1_2

,country,map_participants,binary_label_ids_before_cleaning,excluded_from_common_sample,common_sample,left,right
0,Chile,47574,22071,47,22024,12462,9562
1,France,1443,813,25,788,644,144
2,Brazil,765,499,4,495,373,122

Matplotlib is building the font cache; this may take a moment.

## Predict each participant with a forest trained on other participants

Each participant receives one out-of-fold prediction: the forest producing that prediction never sees their ideological label during training. The coordinates themselves were estimated from policy comparisons, including this participant's comparisons. This evaluates external ideological identification among people already in the map, not prediction for people with no observed policy choices.

Within each country, the fold assignment is computed once and reused by all four specifications. PCA and scaling are fitted on the training fold only. The classifier produces both a binary prediction and a probability of being on the right, which is used for the ROC curve and AUC.

The nested loops below run countries, predictor specifications, and folds in that order. Fold-level progress appears inline. A pooled out-of-fold accuracy weights participants equally, whereas mean fold accuracy weights the ten folds equally. Both are retained. Feature importances are the forest's impurity-based importances, not causal effects.

In [3]:
summary_rows = []
combined_predictions = {}
for country in COUNTRIES:
    frame = frames[country]
    destination = OUT / country
    target = frame.target.to_numpy()
    # Reuse this exact partition for every predictor specification.
    partitions = list(StratifiedKFold(**CV_PARAMETERS).split(frame, target))
    assignment = np.full(len(frame), -1)
    for fold, (_, test) in enumerate(partitions):
        assignment[test] = fold
    assert (assignment >= 0).all()
    assignments = pd.DataFrame(
        {"participant_id": frame.participant_id, "target": target, "fold": assignment}
    )
    display(assignments)
    assignments.to_csv(destination / "fold_assignments.csv", index=False)
    specifications = {
        "coordinates": ["z1", "z2"],
        "demographics": DEMOGRAPHICS[country],
        "combined": DEMOGRAPHICS[country] + ["z1", "z2"],
        "pc1": ["z1", "z2"],
    }
    summaries = {}
    for model_name, features in specifications.items():
        # Test indices write back into participant order, so each row is predicted once.
        probability = np.full(len(frame), np.nan)
        predicted = np.full(len(frame), -1)
        fold_metrics, importance = [], []
        input_matrix = frame[features].to_numpy(dtype=float)
        feature_names = ["PC1"] if model_name == "pc1" else features
        for fold, (train, test) in enumerate(partitions):
            assert not (
                set(frame.participant_id.iloc[train]) & set(frame.participant_id.iloc[test])
            )
            train_x, test_x = input_matrix[train], input_matrix[test]
            # Fit transformations on training participants, then apply to held-out rows.
            if model_name == "pc1":
                pca = PCA(n_components=1, svd_solver="full")
                train_x = pca.fit_transform(train_x)
                test_x = pca.transform(test_x)
            scaler = MinMaxScaler()
            train_x = scaler.fit_transform(train_x)
            test_x = scaler.transform(test_x)
            classifier = RandomForestClassifier(**RF_PARAMETERS)
            before = time.perf_counter()
            classifier.fit(train_x, target[train])
            probability[test] = classifier.predict_proba(test_x)[:, 1]
            predicted[test] = classifier.predict(test_x)
            metrics = {
                "fold": fold,
                "n_train": len(train),
                "n_test": len(test),
                "accuracy": float(accuracy_score(target[test], predicted[test])),
                "recall_left": float(recall_score(target[test], predicted[test], pos_label=0)),
                "recall_right": float(recall_score(target[test], predicted[test], pos_label=1)),
                "auc": float(roc_auc_score(target[test], probability[test])),
                "fit_seconds": time.perf_counter() - before,
            }
            fold_metrics.append(metrics)
            importance.append(dict(zip(feature_names, classifier.feature_importances_)))
            message = f"{country} {model_name}: fold {fold + 1}/{len(partitions)}, accuracy={metrics['accuracy']:.5f}, seconds={metrics['fit_seconds']:.1f}"
            print(message, flush=True)
        assert np.isfinite(probability).all() and (predicted >= 0).all()
        predictions = pd.DataFrame(
            {
                "participant_id": frame.participant_id,
                "target": target,
                "fold": assignment,
                "prediction": predicted,
                "probability_right": probability,
            }
        )
        pd.testing.assert_frame_equal(
            predictions[["participant_id", "target", "fold"]], assignments
        )
        if model_name == "combined":
            combined_predictions[country] = predictions.copy()
        display(predictions)
        predictions.to_csv(destination / f"{model_name}_oof_predictions.csv", index=False)
        fold_table = pd.DataFrame(fold_metrics)
        display(fold_table)
        fold_table.to_csv(destination / f"{model_name}_fold_metrics.csv", index=False)
        fold_table.to_latex(
            destination / f"{model_name}_fold_metrics.tex", index=False, float_format="%.6f"
        )
        importance_table = pd.DataFrame(importance).rename_axis("fold").reset_index()
        display(importance_table)
        importance_table.to_csv(
            destination / f"{model_name}_feature_importance_by_fold.csv", index=False
        )
        importance_table.to_latex(
            destination / f"{model_name}_feature_importance_by_fold.tex",
            index=False,
            float_format="%.6f",
        )
        fpr, tpr, thresholds = roc_curve(target, probability)
        curve = pd.DataFrame({"FPR": fpr, "TPR": tpr, "threshold": thresholds})
        display(curve)
        curve.to_csv(destination / f"{model_name}_roc.csv", index=False)
        scores = fold_table.accuracy.to_numpy()
        summary = {
            "features": feature_names,
            "fold_accuracy_min": float(scores.min()),
            "fold_accuracy_max": float(scores.max()),
            "fold_accuracy_mean": float(scores.mean()),
            "oof_accuracy": float(accuracy_score(target, predicted)),
            "oof_recall_left": float(recall_score(target, predicted, pos_label=0)),
            "oof_recall_right": float(recall_score(target, predicted, pos_label=1)),
            "oof_auc": float(roc_auc_score(target, probability)),
            "confusion_counts_left_right": confusion_matrix(
                target, predicted, labels=[0, 1]
            ).tolist(),
            "confusion_row_normalized_left_right": confusion_matrix(
                target, predicted, labels=[0, 1], normalize="true"
            ).tolist(),
            "mean_feature_importance": pd.DataFrame(importance).mean().to_dict(),
        }
        summaries[model_name] = summary
        summary_rows.append(
            {
                "country": country,
                "model": model_name,
                "n": len(frame),
                **{
                    key: summary[key]
                    for key in [
                        "fold_accuracy_min",
                        "fold_accuracy_max",
                        "fold_accuracy_mean",
                        "oof_accuracy",
                        "oof_recall_left",
                        "oof_recall_right",
                        "oof_auc",
                    ]
                },
            }
        )
    display(summaries)
    (destination / "metrics_summary.json").write_text(json.dumps(summaries, indent=2) + "\n")

summary_table = pd.DataFrame(summary_rows)
display(summary_table)
summary_table.to_csv(OUT / "validation_summary.csv", index=False)
summary_table.to_latex(OUT / "validation_summary.tex", index=False, float_format="%.6f")

                             participant_id  target  fold
0      8bd42737-b140-4db8-af4c-59839922129a       0     8
1      7d2e034a-3270-4429-aeac-418c46bf0d7d       1     0
2      c1b97bb6-03d2-4027-8d54-0dd64a927a6c       0     4
3      883528e9-0599-4d30-9f4c-1daf9cf74082       1     3
4      7fd1210c-b1c0-4bdf-b190-7bfa10fe51d2       0     1
...                                     ...     ...   ...
22019  759b16f2-f527-4f04-85ba-682fd1af8a89       0     4
22020  2e8f5550-d794-411c-b36e-d277e88f5d30       1     5
22021  3ddc9eae-ba7b-4dab-8e43-5c188daf9692       0     0
22022  b7132b2c-5ca4-44ac-b4e7-07e43d4b7547       1     4
22023  1a38e668-bad8-41e5-9e24-050480272131       0     5

[22024 rows x 3 columns]

Chile coordinates: fold 1/10, accuracy=0.80163, seconds=24.7

Chile coordinates: fold 2/10, accuracy=0.81434, seconds=25.2

Chile coordinates: fold 3/10, accuracy=0.79936, seconds=25.9

Chile coordinates: fold 4/10, accuracy=0.80708, seconds=25.7

Chile coordinates: fold 5/10, accuracy=0.79700, seconds=28.1

Chile coordinates: fold 6/10, accuracy=0.79019, seconds=25.3

Chile coordinates: fold 7/10, accuracy=0.80972, seconds=25.2

Chile coordinates: fold 8/10, accuracy=0.81562, seconds=24.9

Chile coordinates: fold 9/10, accuracy=0.80427, seconds=28.6

Chile coordinates: fold 10/10, accuracy=0.79382, seconds=25.3

,participant_id,target,fold,prediction,probability_right
0,8bd42737-b140-4db8-af4c-59839922129a,0,8,1,0.7580
1,7d2e034a-3270-4429-aeac-418c46bf0d7d,1,0,1,0.8210
2,c1b97bb6-03d2-4027-8d54-0dd64a927a6c,0,4,1,0.5220
3,883528e9-0599-4d30-9f4c-1daf9cf74082,1,3,0,0.0315
4,7fd1210c-b1c0-4bdf-b190-7bfa10fe51d2,0,1,0,0.1360
...,...,...,...,...,...
22019,759b16f2-f527-4f04-85ba-682fd1af8a89,0,4,1,0.5040
22020,2e8f5550-d794-411c-b36e-d277e88f5d30,1,5,1,1.0000
22021,3ddc9eae-ba7b-4dab-8e43-5c188daf9692,0,0,0,0.3960
22022,b7132b2c-5ca4-44ac-b4e7-07e43d4b7547,1,4,1,0.7825
22023,1a38e668-bad8-41e5-9e24-050480272131,0,5,1,0.5570

,fold,n_train,n_test,accuracy,recall_left,recall_right,auc,fit_seconds
0,0,19821,2203,0.801634,0.846832,0.742678,0.865605,24.740450
1,1,19821,2203,0.814344,0.852446,0.764644,0.875423,25.199937
2,2,19821,2203,0.799365,0.837881,0.749216,0.859549,25.874487
3,3,19821,2203,0.807081,0.829856,0.777429,0.868402,25.658937
4,4,19822,2202,0.797003,0.819422,0.767782,0.868087,28.097355
5,5,19822,2202,0.790191,0.814607,0.758368,0.854366,25.263142
6,6,19822,2202,0.809718,0.840289,0.769874,0.877480,25.158211
7,7,19822,2202,0.815622,0.853933,0.765690,0.882111,24.923573
8,8,19822,2202,0.804269,0.832263,0.767782,0.867035,28.627469
9,9,19822,2202,0.793824,0.848315,0.722803,0.852833,25.290957

   fold        z1        z2
0     0  0.439072  0.560928
1     1  0.441292  0.558708
2     2  0.438187  0.561813
3     3  0.440308  0.559692
4     4  0.441803  0.558197
5     5  0.439114  0.560886
6     6  0.440015  0.559985
7     7  0.439827  0.560173
8     8  0.439254  0.560746
9     9  0.439922  0.560078

           FPR       TPR  threshold
0     0.000000  0.000000        inf
1     0.000883  0.020079     1.0000
2     0.001284  0.032315     0.9995
3     0.001685  0.039531     0.9990
4     0.001846  0.047793     0.9985
...        ...       ...        ...
1939  0.922484  0.994457     0.0020
1940  0.932194  0.995503     0.0015
1941  0.944953  0.996235     0.0010
1942  0.962526  0.997804     0.0005
1943  1.000000  1.000000     0.0000

[1944 rows x 3 columns]

Chile demographics: fold 1/10, accuracy=0.54517, seconds=6.9

Chile demographics: fold 2/10, accuracy=0.56332, seconds=6.7

Chile demographics: fold 3/10, accuracy=0.56196, seconds=6.7

Chile demographics: fold 4/10, accuracy=0.57921, seconds=6.7

Chile demographics: fold 5/10, accuracy=0.56812, seconds=8.0

Chile demographics: fold 6/10, accuracy=0.56630, seconds=7.8

Chile demographics: fold 7/10, accuracy=0.55450, seconds=9.3

Chile demographics: fold 8/10, accuracy=0.56131, seconds=8.1

Chile demographics: fold 9/10, accuracy=0.55722, seconds=6.7

Chile demographics: fold 10/10, accuracy=0.55450, seconds=6.7

,participant_id,target,fold,prediction,probability_right
0,8bd42737-b140-4db8-af4c-59839922129a,0,8,0,0.361997
1,7d2e034a-3270-4429-aeac-418c46bf0d7d,1,0,0,0.467993
2,c1b97bb6-03d2-4027-8d54-0dd64a927a6c,0,4,0,0.369395
3,883528e9-0599-4d30-9f4c-1daf9cf74082,1,3,1,0.521735
4,7fd1210c-b1c0-4bdf-b190-7bfa10fe51d2,0,1,0,0.208404
...,...,...,...,...,...
22019,759b16f2-f527-4f04-85ba-682fd1af8a89,0,4,0,0.494019
22020,2e8f5550-d794-411c-b36e-d277e88f5d30,1,5,1,0.809950
22021,3ddc9eae-ba7b-4dab-8e43-5c188daf9692,0,0,0,0.162810
22022,b7132b2c-5ca4-44ac-b4e7-07e43d4b7547,1,4,0,0.472524
22023,1a38e668-bad8-41e5-9e24-050480272131,0,5,1,0.871381

,fold,n_train,n_test,accuracy,recall_left,recall_right,auc,fit_seconds
0,0,19821,2203,0.545166,0.723336,0.312762,0.554651,6.854325
1,1,19821,2203,0.563323,0.712109,0.369247,0.569187,6.684828
2,2,19821,2203,0.561961,0.700642,0.381400,0.575497,6.725083
3,3,19821,2203,0.579210,0.752809,0.353187,0.582276,6.735589
4,4,19822,2202,0.568120,0.715088,0.376569,0.576148,8.041427
5,5,19822,2202,0.566303,0.722311,0.362971,0.570168,7.789805
6,6,19822,2202,0.554496,0.695827,0.370293,0.565306,9.305710
7,7,19822,2202,0.561308,0.723114,0.350418,0.575680,8.143977
8,8,19822,2202,0.557221,0.723114,0.341004,0.556625,6.672717
9,9,19822,2202,0.554496,0.687801,0.380753,0.552075,6.658048

   fold       age       sex    region
0     0  0.607787  0.111074  0.281139
1     1  0.610835  0.110062  0.279102
2     2  0.597002  0.105208  0.297790
3     3  0.602700  0.102955  0.294345
4     4  0.607841  0.109711  0.282449
5     5  0.592329  0.112237  0.295433
6     6  0.609385  0.113196  0.277419
7     7  0.615821  0.107610  0.276569
8     8  0.612308  0.107908  0.279783
9     9  0.610105  0.108860  0.281035

           FPR       TPR  threshold
0     0.000000  0.000000        inf
1     0.000241  0.000000   0.998107
2     0.000321  0.000209   0.997970
3     0.000481  0.000209   0.997494
4     0.000562  0.000209   0.996750
...        ...       ...        ...
4314  0.996229  0.998745   0.000143
4315  0.996229  0.998850   0.000115
4316  0.996389  0.998850   0.000089
4317  0.996630  0.998850   0.000063
4318  1.000000  1.000000   0.000000

[4319 rows x 3 columns]

Chile combined: fold 1/10, accuracy=0.80617, seconds=24.2

Chile combined: fold 2/10, accuracy=0.82842, seconds=28.9

Chile combined: fold 3/10, accuracy=0.80935, seconds=24.1

Chile combined: fold 4/10, accuracy=0.81934, seconds=25.6

Chile combined: fold 5/10, accuracy=0.82062, seconds=24.3

Chile combined: fold 6/10, accuracy=0.80109, seconds=24.0

Chile combined: fold 7/10, accuracy=0.80699, seconds=24.3

Chile combined: fold 8/10, accuracy=0.83197, seconds=24.5

Chile combined: fold 9/10, accuracy=0.81789, seconds=24.6

Chile combined: fold 10/10, accuracy=0.81335, seconds=24.6

,participant_id,target,fold,prediction,probability_right
0,8bd42737-b140-4db8-af4c-59839922129a,0,8,1,0.8710
1,7d2e034a-3270-4429-aeac-418c46bf0d7d,1,0,1,0.8315
2,c1b97bb6-03d2-4027-8d54-0dd64a927a6c,0,4,1,0.6230
3,883528e9-0599-4d30-9f4c-1daf9cf74082,1,3,0,0.0280
4,7fd1210c-b1c0-4bdf-b190-7bfa10fe51d2,0,1,0,0.0850
...,...,...,...,...,...
22019,759b16f2-f527-4f04-85ba-682fd1af8a89,0,4,0,0.2845
22020,2e8f5550-d794-411c-b36e-d277e88f5d30,1,5,1,0.9930
22021,3ddc9eae-ba7b-4dab-8e43-5c188daf9692,0,0,1,0.5705
22022,b7132b2c-5ca4-44ac-b4e7-07e43d4b7547,1,4,1,0.7510
22023,1a38e668-bad8-41e5-9e24-050480272131,0,5,1,0.7015

,fold,n_train,n_test,accuracy,recall_left,recall_right,auc,fit_seconds
0,0,19821,2203,0.806173,0.848436,0.751046,0.876059,24.196917
1,1,19821,2203,0.828416,0.870088,0.774059,0.891005,28.892950
2,2,19821,2203,0.809351,0.847512,0.759666,0.871335,24.086006
3,3,19821,2203,0.819337,0.855538,0.772205,0.881660,25.591393
4,4,19822,2202,0.820618,0.842697,0.791841,0.880564,24.320556
5,5,19822,2202,0.801090,0.832263,0.760460,0.864699,23.971713
6,6,19822,2202,0.806994,0.836276,0.768828,0.880811,24.270714
7,7,19822,2202,0.831971,0.857945,0.798117,0.898013,24.469008
8,8,19822,2202,0.817893,0.849117,0.777197,0.877643,24.614893
9,9,19822,2202,0.813351,0.857143,0.756276,0.869215,24.617749

   fold       age       sex    region        z1        z2
0     0  0.126541  0.014792  0.052798  0.328153  0.477716
1     1  0.126781  0.014730  0.053308  0.331031  0.474151
2     2  0.125949  0.014822  0.053323  0.327243  0.478663
3     3  0.126669  0.014459  0.052539  0.328753  0.477580
4     4  0.125656  0.014921  0.052795  0.331108  0.475520
5     5  0.125335  0.014348  0.053072  0.330115  0.477129
6     6  0.126325  0.014761  0.052487  0.329271  0.477156
7     7  0.128183  0.014740  0.052594  0.328734  0.475749
8     8  0.125945  0.014957  0.052283  0.329748  0.477067
9     9  0.125779  0.014825  0.052262  0.329633  0.477501

           FPR       TPR  threshold
0     0.000000  0.000000        inf
1     0.000000  0.001046     1.0000
2     0.000080  0.003347     0.9995
3     0.000080  0.008157     0.9985
4     0.000080  0.010458     0.9980
...        ...       ...        ...
1945  0.981704  0.999373     0.0020
1946  0.986680  0.999686     0.0015
1947  0.991976  0.999791     0.0010
1948  0.996148  0.999895     0.0005
1949  1.000000  1.000000     0.0000

[1950 rows x 3 columns]

Chile pc1: fold 1/10, accuracy=0.72583, seconds=30.4

Chile pc1: fold 2/10, accuracy=0.75125, seconds=30.5

Chile pc1: fold 3/10, accuracy=0.74399, seconds=30.8

Chile pc1: fold 4/10, accuracy=0.75034, seconds=31.3

Chile pc1: fold 5/10, accuracy=0.75386, seconds=31.5

Chile pc1: fold 6/10, accuracy=0.73206, seconds=31.1

Chile pc1: fold 7/10, accuracy=0.73479, seconds=30.5

Chile pc1: fold 8/10, accuracy=0.75568, seconds=30.1

Chile pc1: fold 9/10, accuracy=0.74886, seconds=31.0

Chile pc1: fold 10/10, accuracy=0.74205, seconds=30.6

,participant_id,target,fold,prediction,probability_right
0,8bd42737-b140-4db8-af4c-59839922129a,0,8,1,0.9140
1,7d2e034a-3270-4429-aeac-418c46bf0d7d,1,0,1,0.7555
2,c1b97bb6-03d2-4027-8d54-0dd64a927a6c,0,4,0,0.3620
3,883528e9-0599-4d30-9f4c-1daf9cf74082,1,3,0,0.0015
4,7fd1210c-b1c0-4bdf-b190-7bfa10fe51d2,0,1,0,0.0000
...,...,...,...,...,...
22019,759b16f2-f527-4f04-85ba-682fd1af8a89,0,4,0,0.0350
22020,2e8f5550-d794-411c-b36e-d277e88f5d30,1,5,1,0.7745
22021,3ddc9eae-ba7b-4dab-8e43-5c188daf9692,0,0,1,0.8790
22022,b7132b2c-5ca4-44ac-b4e7-07e43d4b7547,1,4,1,1.0000
22023,1a38e668-bad8-41e5-9e24-050480272131,0,5,1,0.9590

,fold,n_train,n_test,accuracy,recall_left,recall_right,auc,fit_seconds
0,0,19821,2203,0.725828,0.757819,0.684100,0.827532,30.445787
1,1,19821,2203,0.751248,0.777867,0.716527,0.844732,30.527847
2,2,19821,2203,0.743985,0.768058,0.712644,0.835788,30.771537
3,3,19821,2203,0.750340,0.786517,0.703239,0.844533,31.319846
4,4,19822,2202,0.753860,0.785714,0.712343,0.843449,31.484226
5,5,19822,2202,0.732062,0.745586,0.714435,0.823686,31.054500
6,6,19822,2202,0.734787,0.756019,0.707113,0.837412,30.490623
7,7,19822,2202,0.755677,0.779294,0.724895,0.849615,30.068671
8,8,19822,2202,0.748865,0.776083,0.713389,0.838246,31.033018
9,9,19822,2202,0.742053,0.779294,0.693515,0.832512,30.645809

   fold  PC1
0     0  1.0
1     1  1.0
2     2  1.0
3     3  1.0
4     4  1.0
5     5  1.0
6     6  1.0
7     7  1.0
8     8  1.0
9     9  1.0

           FPR       TPR  threshold
0     0.000000  0.000000        inf
1     0.020382  0.256641     1.0000
2     0.023993  0.281949     0.9995
3     0.026160  0.297009     0.9990
4     0.027604  0.304957     0.9985
...        ...       ...        ...
1230  0.614749  0.948651     0.0020
1231  0.625662  0.950847     0.0015
1232  0.641952  0.955449     0.0010
1233  0.668352  0.961933     0.0005
1234  1.000000  1.000000     0.0000

[1235 rows x 3 columns]

{'coordinates': {'features': ['z1', 'z2'],
  'fold_accuracy_min': 0.7901907356948229,
  'fold_accuracy_max': 0.815622161671208,
  'fold_accuracy_mean': 0.803305067031457,
  'oof_accuracy': 0.8033054849255358,
  'oof_recall_left': 0.8375862622372011,
  'oof_recall_right': 0.7586279021125287,
  'oof_auc': 0.8670722141094327,
  'confusion_counts_left_right': [[10438, 2024], [2308, 7254]],
  'confusion_row_normalized_left_right': [[0.8375862622372011,
    0.1624137377627989],
   [0.24137209788747124, 0.7586279021125287]],
  'mean_feature_importance': {'z1': 0.43987924045298293,
   'z2': 0.560120759547017}},
 'demographics': {'features': ['age', 'sex', 'region'],
  'fold_accuracy_min': 0.5451656831593282,
  'fold_accuracy_max': 0.5792101679527917,
  'fold_accuracy_mean': 0.5611603242708832,
  'oof_accuracy': 0.5611605521249546,
  'oof_recall_left': 0.7156154710319371,
  'oof_recall_right': 0.35986195356619954,
  'oof_auc': 0.5672655707905474,
  'confusion_counts_left_right': [[8918, 3544], [6121, 3441]],
  'confusion_row_normalized_left_right': [[0.7156154710319371,
    0.28438452896806293],
   [0.6401380464338005, 0.35986195356619954]],
  'mean_feature_importance': {'age': 0.6066114228257018,
   'sex': 0.10888207667146721,
   'region': 0.284506500502831}},
 'combined': {'features': ['age', 'sex', 'region', 'z1', 'z2'],
  'fold_accuracy_min': 0.8010899182561307,
  'fold_accuracy_max': 0.8319709355131698,
  'fold_accuracy_mean': 0.8155193788669812,
  'oof_accuracy': 0.8155194333454413,
  'oof_recall_left': 0.849703097416145,
  'oof_recall_right': 0.7709684166492365,
  'oof_auc': 0.8792069871073613,
  'confusion_counts_left_right': [[10589, 1873], [2190, 7372]],
  'confusion_row_normalized_left_right': [[0.849703097416145,
    0.15029690258385492],
   [0.22903158335076343, 0.7709684166492365]],
  'mean_feature_importance': {'age': 0.12631635605937228,
   'sex': 0.014735528645454516,
   'region': 0.05274603450941612,
   'z1': 0.3293789007182014,
   'z2': 0.47682318006755564}},
 'pc1': {'features': ['PC1'],
  'fold_accuracy_min': 0.7258284157966409,
  'fold_accuracy_max': 0.7556766575840145,
  'fold_accuracy_mean': 0.7438705085089568,
  'oof_accuracy': 0.7438703232836905,
  'oof_recall_left': 0.7712245225485476,
  'oof_recall_right': 0.7082200376490274,
  'oof_auc': 0.8377426758227673,
  'confusion_counts_left_right': [[9611, 2851], [2790, 6772]],
  'confusion_row_normalized_left_right': [[0.7712245225485476,
    0.2287754774514524],
   [0.2917799623509726, 0.7082200376490274]],
  'mean_feature_importance': {'PC1': 1.0}}}

                           participant_id  target  fold
0    e9001e65-7aa1-468d-a7c6-dca4ad023e59       0     9
1    41e3bf3a-e792-4521-8d3a-8f974f329345       0     9
2    a664ff56-e303-4ab5-8841-bc950222e75f       0     9
3    7490cb32-18ba-4572-9310-c0c3801438d0       1     9
4    fecf3440-84f3-4bcb-b2c4-f6c939d80ec7       0     4
..                                    ...     ...   ...
783  9026410e-9aa7-4bf8-aafa-8dbd26c94c63       1     1
784  67e9a740-4137-4834-9331-a54929c5e6a9       0     1
785  48243d8e-ab20-4379-b9ba-ba76c4cde2f3       0     4
786  a7adb7e7-e526-49b9-93d5-563f75aa7714       0     6
787  23dc2d73-ff4b-4b6b-b4fb-35380d616e18       0     1

[788 rows x 3 columns]

France coordinates: fold 1/10, accuracy=0.93671, seconds=1.5

France coordinates: fold 2/10, accuracy=0.88608, seconds=1.5

France coordinates: fold 3/10, accuracy=0.91139, seconds=1.4

France coordinates: fold 4/10, accuracy=0.92405, seconds=1.5

France coordinates: fold 5/10, accuracy=0.87342, seconds=1.5

France coordinates: fold 6/10, accuracy=0.94937, seconds=1.5

France coordinates: fold 7/10, accuracy=0.86076, seconds=1.5

France coordinates: fold 8/10, accuracy=0.91139, seconds=1.6

France coordinates: fold 9/10, accuracy=0.93590, seconds=1.5

France coordinates: fold 10/10, accuracy=0.93590, seconds=1.5

,participant_id,target,fold,prediction,probability_right
0,e9001e65-7aa1-468d-a7c6-dca4ad023e59,0,9,0,0.0075
1,41e3bf3a-e792-4521-8d3a-8f974f329345,0,9,0,0.0000
2,a664ff56-e303-4ab5-8841-bc950222e75f,0,9,0,0.0000
3,7490cb32-18ba-4572-9310-c0c3801438d0,1,9,1,0.9755
4,fecf3440-84f3-4bcb-b2c4-f6c939d80ec7,0,4,0,0.0065
...,...,...,...,...,...
783,9026410e-9aa7-4bf8-aafa-8dbd26c94c63,1,1,1,0.6110
784,67e9a740-4137-4834-9331-a54929c5e6a9,0,1,0,0.0000
785,48243d8e-ab20-4379-b9ba-ba76c4cde2f3,0,4,0,0.1055
786,a7adb7e7-e526-49b9-93d5-563f75aa7714,0,6,0,0.0000
787,23dc2d73-ff4b-4b6b-b4fb-35380d616e18,0,1,1,0.7205

,fold,n_train,n_test,accuracy,recall_left,recall_right,auc,fit_seconds
0,0,709,79,0.936709,0.984615,0.714286,0.915934,1.468116
1,1,709,79,0.886076,0.907692,0.785714,0.940659,1.486213
2,2,709,79,0.911392,0.923077,0.857143,0.985714,1.449163
3,3,709,79,0.924051,0.984615,0.642857,0.950549,1.482269
4,4,709,79,0.873418,0.953125,0.533333,0.927083,1.476161
5,5,709,79,0.949367,0.984375,0.800000,0.942187,1.508968
6,6,709,79,0.860759,0.953125,0.466667,0.897917,1.462983
7,7,709,79,0.911392,0.968750,0.666667,0.920833,1.604546
8,8,710,78,0.935897,0.953125,0.857143,0.970982,1.548791
9,9,710,78,0.935897,0.984375,0.714286,0.975446,1.517014

   fold        z1        z2
0     0  0.583084  0.416916
1     1  0.569554  0.430446
2     2  0.560234  0.439766
3     3  0.567804  0.432196
4     4  0.570903  0.429097
5     5  0.571343  0.428657
6     6  0.560696  0.439304
7     7  0.584337  0.415663
8     8  0.565394  0.434606
9     9  0.568890  0.431110

          FPR       TPR  threshold
0    0.000000  0.000000        inf
1    0.000000  0.055556     1.0000
2    0.000000  0.069444     0.9995
3    0.001553  0.090278     0.9990
4    0.001553  0.118056     0.9985
..        ...       ...        ...
143  0.406832  0.986111     0.0020
144  0.411491  0.986111     0.0015
145  0.422360  0.986111     0.0010
146  0.440994  0.986111     0.0005
147  1.000000  1.000000     0.0000

[148 rows x 3 columns]

France demographics: fold 1/10, accuracy=0.82278, seconds=1.6

France demographics: fold 2/10, accuracy=0.82278, seconds=1.5

France demographics: fold 3/10, accuracy=0.82278, seconds=1.5

France demographics: fold 4/10, accuracy=0.82278, seconds=1.5

France demographics: fold 5/10, accuracy=0.81013, seconds=1.5

France demographics: fold 6/10, accuracy=0.81013, seconds=1.5

France demographics: fold 7/10, accuracy=0.81013, seconds=1.5

France demographics: fold 8/10, accuracy=0.81013, seconds=1.5

France demographics: fold 9/10, accuracy=0.82051, seconds=1.4

France demographics: fold 10/10, accuracy=0.82051, seconds=1.5

,participant_id,target,fold,prediction,probability_right
0,e9001e65-7aa1-468d-a7c6-dca4ad023e59,0,9,0,0.152318
1,41e3bf3a-e792-4521-8d3a-8f974f329345,0,9,0,0.152318
2,a664ff56-e303-4ab5-8841-bc950222e75f,0,9,0,0.093515
3,7490cb32-18ba-4572-9310-c0c3801438d0,1,9,0,0.222210
4,fecf3440-84f3-4bcb-b2c4-f6c939d80ec7,0,4,0,0.102937
...,...,...,...,...,...
783,9026410e-9aa7-4bf8-aafa-8dbd26c94c63,1,1,0,0.234549
784,67e9a740-4137-4834-9331-a54929c5e6a9,0,1,0,0.000000
785,48243d8e-ab20-4379-b9ba-ba76c4cde2f3,0,4,0,0.106923
786,a7adb7e7-e526-49b9-93d5-563f75aa7714,0,6,0,0.236160
787,23dc2d73-ff4b-4b6b-b4fb-35380d616e18,0,1,0,0.234549

,fold,n_train,n_test,accuracy,recall_left,recall_right,auc,fit_seconds
0,0,709,79,0.822785,1.0,0.0,0.593407,1.599908
1,1,709,79,0.822785,1.0,0.0,0.531868,1.485780
2,2,709,79,0.822785,1.0,0.0,0.612088,1.499144
3,3,709,79,0.822785,1.0,0.0,0.569780,1.498571
4,4,709,79,0.810127,1.0,0.0,0.478125,1.514232
5,5,709,79,0.810127,1.0,0.0,0.552083,1.484085
6,6,709,79,0.810127,1.0,0.0,0.518750,1.494933
7,7,709,79,0.810127,1.0,0.0,0.522396,1.452348
8,8,710,78,0.820513,1.0,0.0,0.497210,1.441839
9,9,710,78,0.820513,1.0,0.0,0.691406,1.459563

   fold       age       sex
0     0  0.672350  0.327650
1     1  0.623236  0.376764
2     2  0.670894  0.329106
3     3  0.595084  0.404916
4     4  0.489471  0.510529
5     5  0.653726  0.346274
6     6  0.591904  0.408096
7     7  0.629180  0.370820
8     8  0.515080  0.484920
9     9  0.580443  0.419557

         FPR       TPR  threshold
0   0.000000  0.000000        inf
1   0.004658  0.000000   0.272529
2   0.007764  0.000000   0.241203
3   0.043478  0.041667   0.237587
4   0.141304  0.166667   0.235602
..       ...       ...        ...
69  0.975155  0.993056   0.053312
70  0.976708  0.993056   0.053008
71  0.979814  0.993056   0.052944
72  0.993789  0.993056   0.000056
73  1.000000  1.000000   0.000000

[74 rows x 3 columns]

France combined: fold 1/10, accuracy=0.93671, seconds=1.5

France combined: fold 2/10, accuracy=0.88608, seconds=1.5

France combined: fold 3/10, accuracy=0.94937, seconds=1.5

France combined: fold 4/10, accuracy=0.89873, seconds=1.5

France combined: fold 5/10, accuracy=0.87342, seconds=1.5

France combined: fold 6/10, accuracy=0.94937, seconds=1.5

France combined: fold 7/10, accuracy=0.86076, seconds=1.5

France combined: fold 8/10, accuracy=0.87342, seconds=1.5

France combined: fold 9/10, accuracy=0.93590, seconds=1.5

France combined: fold 10/10, accuracy=0.94872, seconds=1.5

,participant_id,target,fold,prediction,probability_right
0,e9001e65-7aa1-468d-a7c6-dca4ad023e59,0,9,0,0.0120
1,41e3bf3a-e792-4521-8d3a-8f974f329345,0,9,0,0.0000
2,a664ff56-e303-4ab5-8841-bc950222e75f,0,9,0,0.0000
3,7490cb32-18ba-4572-9310-c0c3801438d0,1,9,1,0.9810
4,fecf3440-84f3-4bcb-b2c4-f6c939d80ec7,0,4,0,0.0050
...,...,...,...,...,...
783,9026410e-9aa7-4bf8-aafa-8dbd26c94c63,1,1,1,0.6330
784,67e9a740-4137-4834-9331-a54929c5e6a9,0,1,0,0.0000
785,48243d8e-ab20-4379-b9ba-ba76c4cde2f3,0,4,0,0.0635
786,a7adb7e7-e526-49b9-93d5-563f75aa7714,0,6,0,0.0000
787,23dc2d73-ff4b-4b6b-b4fb-35380d616e18,0,1,1,0.7175

,fold,n_train,n_test,accuracy,recall_left,recall_right,auc,fit_seconds
0,0,709,79,0.936709,0.969231,0.785714,0.937363,1.495402
1,1,709,79,0.886076,0.923077,0.714286,0.938462,1.499543
2,2,709,79,0.949367,0.969231,0.857143,0.990110,1.506673
3,3,709,79,0.898734,0.969231,0.571429,0.958242,1.505114
4,4,709,79,0.873418,0.953125,0.533333,0.918750,1.490304
5,5,709,79,0.949367,0.984375,0.800000,0.930208,1.474633
6,6,709,79,0.860759,0.953125,0.466667,0.927083,1.498648
7,7,709,79,0.873418,0.937500,0.600000,0.913542,1.485542
8,8,710,78,0.935897,0.953125,0.857143,0.982143,1.490257
9,9,710,78,0.948718,1.000000,0.714286,0.985491,1.504772

   fold       age       sex        z1        z2
0     0  0.039305  0.013448  0.608496  0.338751
1     1  0.042809  0.012992  0.589132  0.355066
2     2  0.043710  0.012641  0.579746  0.363903
3     3  0.043037  0.013982  0.587058  0.355922
4     4  0.044091  0.013362  0.591093  0.351454
5     5  0.043797  0.012836  0.592589  0.350778
6     6  0.043152  0.013425  0.577425  0.365998
7     7  0.040152  0.013623  0.608063  0.338162
8     8  0.043714  0.013511  0.585501  0.357274
9     9  0.043911  0.014170  0.587217  0.354701

          FPR       TPR  threshold
0    0.000000  0.000000        inf
1    0.000000  0.020833     1.0000
2    0.000000  0.034722     0.9995
3    0.000000  0.048611     0.9980
4    0.000000  0.069444     0.9975
..        ...       ...        ...
147  0.434783  0.993056     0.0020
148  0.447205  0.993056     0.0015
149  0.465839  0.993056     0.0010
150  0.496894  0.993056     0.0005
151  1.000000  1.000000     0.0000

[152 rows x 3 columns]

France pc1: fold 1/10, accuracy=0.89873, seconds=1.5

France pc1: fold 2/10, accuracy=0.79747, seconds=1.5

France pc1: fold 3/10, accuracy=0.94937, seconds=1.5

France pc1: fold 4/10, accuracy=0.84810, seconds=1.5

France pc1: fold 5/10, accuracy=0.88608, seconds=1.5

France pc1: fold 6/10, accuracy=0.91139, seconds=1.5

France pc1: fold 7/10, accuracy=0.84810, seconds=1.7

France pc1: fold 8/10, accuracy=0.81013, seconds=1.6

France pc1: fold 9/10, accuracy=0.92308, seconds=1.5

France pc1: fold 10/10, accuracy=0.92308, seconds=1.5

,participant_id,target,fold,prediction,probability_right
0,e9001e65-7aa1-468d-a7c6-dca4ad023e59,0,9,0,0.0000
1,41e3bf3a-e792-4521-8d3a-8f974f329345,0,9,0,0.0000
2,a664ff56-e303-4ab5-8841-bc950222e75f,0,9,0,0.0000
3,7490cb32-18ba-4572-9310-c0c3801438d0,1,9,1,0.9670
4,fecf3440-84f3-4bcb-b2c4-f6c939d80ec7,0,4,0,0.0000
...,...,...,...,...,...
783,9026410e-9aa7-4bf8-aafa-8dbd26c94c63,1,1,1,0.9065
784,67e9a740-4137-4834-9331-a54929c5e6a9,0,1,0,0.0000
785,48243d8e-ab20-4379-b9ba-ba76c4cde2f3,0,4,0,0.0000
786,a7adb7e7-e526-49b9-93d5-563f75aa7714,0,6,0,0.0000
787,23dc2d73-ff4b-4b6b-b4fb-35380d616e18,0,1,1,0.6405

,fold,n_train,n_test,accuracy,recall_left,recall_right,auc,fit_seconds
0,0,709,79,0.898734,0.938462,0.714286,0.898901,1.466846
1,1,709,79,0.797468,0.830769,0.642857,0.898901,1.465795
2,2,709,79,0.949367,0.938462,1.000000,0.996703,1.488501
3,3,709,79,0.848101,0.938462,0.428571,0.871429,1.476060
4,4,709,79,0.886076,0.968750,0.533333,0.897396,1.526763
5,5,709,79,0.911392,0.937500,0.800000,0.936458,1.492042
6,6,709,79,0.848101,0.937500,0.466667,0.861458,1.650315
7,7,709,79,0.810127,0.890625,0.466667,0.796875,1.625218
8,8,710,78,0.923077,0.953125,0.785714,0.925781,1.483485
9,9,710,78,0.923077,0.968750,0.714286,0.943080,1.457441

   fold  PC1
0     0  1.0
1     1  1.0
2     2  1.0
3     3  1.0
4     4  1.0
5     5  1.0
6     6  1.0
7     7  1.0
8     8  1.0
9     9  1.0

         FPR       TPR  threshold
0   0.000000  0.000000        inf
1   0.004658  0.326389     1.0000
2   0.004658  0.354167     0.9995
3   0.004658  0.368056     0.9990
4   0.004658  0.395833     0.9950
..       ...       ...        ...
92  0.214286  0.902778     0.0025
93  0.223602  0.902778     0.0015
94  0.225155  0.902778     0.0010
95  0.239130  0.909722     0.0005
96  1.000000  1.000000     0.0000

[97 rows x 3 columns]

{'coordinates': {'features': ['z1', 'z2'],
  'fold_accuracy_min': 0.8607594936708861,
  'fold_accuracy_max': 0.9493670886075949,
  'fold_accuracy_mean': 0.9124959428756897,
  'oof_accuracy': 0.9124365482233503,
  'oof_recall_left': 0.9596273291925466,
  'oof_recall_right': 0.7013888888888888,
  'oof_auc': 0.9418079278812975,
  'confusion_counts_left_right': [[618, 26], [43, 101]],
  'confusion_row_normalized_left_right': [[0.9596273291925466,
    0.040372670807453416],
   [0.2986111111111111, 0.7013888888888888]],
  'mean_feature_importance': {'z1': 0.5702238971882243,
   'z2': 0.42977610281177564}},
 'demographics': {'features': ['age', 'sex'],
  'fold_accuracy_min': 0.810126582278481,
  'fold_accuracy_max': 0.8227848101265823,
  'fold_accuracy_mean': 0.8172671210645894,
  'oof_accuracy': 0.817258883248731,
  'oof_recall_left': 1.0,
  'oof_recall_right': 0.0,
  'oof_auc': 0.5429121376811595,
  'confusion_counts_left_right': [[644, 0], [144, 0]],
  'confusion_row_normalized_left_right': [[1.0, 0.0], [1.0, 0.0]],
  'mean_feature_importance': {'age': 0.6021368623498369,
   'sex': 0.3978631376501631}},
 'combined': {'features': ['age', 'sex', 'z1', 'z2'],
  'fold_accuracy_min': 0.8607594936708861,
  'fold_accuracy_max': 0.9493670886075949,
  'fold_accuracy_mean': 0.9112463485881207,
  'oof_accuracy': 0.9111675126903553,
  'oof_recall_left': 0.9611801242236024,
  'oof_recall_right': 0.6875,
  'oof_auc': 0.9457977484472049,
  'confusion_counts_left_right': [[619, 25], [45, 99]],
  'confusion_row_normalized_left_right': [[0.9611801242236024,
    0.03881987577639751],
   [0.3125, 0.6875]],
  'mean_feature_importance': {'age': 0.04276801622102871,
   'sex': 0.013398919021718516,
   'z1': 0.590632062032648,
   'z2': 0.35320100272460475}},
 'pc1': {'features': ['PC1'],
  'fold_accuracy_min': 0.7974683544303798,
  'fold_accuracy_max': 0.9493670886075949,
  'fold_accuracy_mean': 0.8795520934761442,
  'oof_accuracy': 0.8794416243654822,
  'oof_recall_left': 0.9301242236024845,
  'oof_recall_right': 0.6527777777777778,
  'oof_auc': 0.9019528554175295,
  'confusion_counts_left_right': [[599, 45], [50, 94]],
  'confusion_row_normalized_left_right': [[0.9301242236024845,
    0.06987577639751552],
   [0.3472222222222222, 0.6527777777777778]],
  'mean_feature_importance': {'PC1': 1.0}}}

                           participant_id  target  fold
0    e3428c81-c1a3-4139-9deb-ab2b9aae481d       0     8
1    248860f8-a008-4207-84fd-a88cdc02e3f1       0     0
2    f3d2061a-9ffa-4fc2-bf46-f9990b6055ec       0     0
3    457cc0fc-957a-4984-a685-587b0686d18d       0     8
4    fc8481a9-7975-43f3-8a76-c054d51e73ea       1     5
..                                    ...     ...   ...
490  33c490b5-f5e4-4db9-8d77-4f76fd0d363f       0     2
491  5d5f537f-a895-49ed-966d-a5b31539155d       1     5
492  035fef84-952f-40cf-b6bc-59419ebc4234       1     1
493  730666d4-bf22-4c25-9df0-cd447cd72100       1     3
494  464341cf-d0ec-4067-8905-a50b34a7fd90       1     2

[495 rows x 3 columns]

Brazil coordinates: fold 1/10, accuracy=0.84000, seconds=1.4

Brazil coordinates: fold 2/10, accuracy=0.92000, seconds=1.4

Brazil coordinates: fold 3/10, accuracy=0.90000, seconds=1.4

Brazil coordinates: fold 4/10, accuracy=0.92000, seconds=1.4

Brazil coordinates: fold 5/10, accuracy=0.86000, seconds=1.4

Brazil coordinates: fold 6/10, accuracy=0.93878, seconds=1.4

Brazil coordinates: fold 7/10, accuracy=0.83673, seconds=1.4

Brazil coordinates: fold 8/10, accuracy=0.85714, seconds=1.4

Brazil coordinates: fold 9/10, accuracy=0.83673, seconds=1.4

Brazil coordinates: fold 10/10, accuracy=0.81633, seconds=1.4

,participant_id,target,fold,prediction,probability_right
0,e3428c81-c1a3-4139-9deb-ab2b9aae481d,0,8,0,0.0010
1,248860f8-a008-4207-84fd-a88cdc02e3f1,0,0,1,0.5500
2,f3d2061a-9ffa-4fc2-bf46-f9990b6055ec,0,0,0,0.0010
3,457cc0fc-957a-4984-a685-587b0686d18d,0,8,0,0.0325
4,fc8481a9-7975-43f3-8a76-c054d51e73ea,1,5,1,0.9775
...,...,...,...,...,...
490,33c490b5-f5e4-4db9-8d77-4f76fd0d363f,0,2,0,0.1040
491,5d5f537f-a895-49ed-966d-a5b31539155d,1,5,1,0.8875
492,035fef84-952f-40cf-b6bc-59419ebc4234,1,1,1,0.8910
493,730666d4-bf22-4c25-9df0-cd447cd72100,1,3,1,0.8960
494,464341cf-d0ec-4067-8905-a50b34a7fd90,1,2,1,0.8750

,fold,n_train,n_test,accuracy,recall_left,recall_right,auc,fit_seconds
0,0,445,50,0.840000,0.921053,0.583333,0.910088,1.368920
1,1,445,50,0.920000,0.947368,0.833333,0.956140,1.367909
2,2,445,50,0.900000,0.947368,0.750000,0.947368,1.371695
3,3,445,50,0.920000,0.891892,1.000000,0.958420,1.359658
4,4,445,50,0.860000,0.945946,0.615385,0.958420,1.399967
5,5,446,49,0.938776,0.972973,0.833333,0.986486,1.390848
6,6,446,49,0.836735,0.837838,0.833333,0.889640,1.387599
7,7,446,49,0.857143,0.891892,0.750000,0.943694,1.385622
8,8,446,49,0.836735,0.945946,0.500000,0.868243,1.380401
9,9,446,49,0.816327,0.918919,0.500000,0.923423,1.395977

   fold        z1        z2
0     0  0.771129  0.228871
1     1  0.758125  0.241875
2     2  0.755814  0.244186
3     3  0.755734  0.244266
4     4  0.768200  0.231800
5     5  0.752635  0.247365
6     6  0.772133  0.227867
7     7  0.765139  0.234861
8     8  0.772765  0.227235
9     9  0.768103  0.231897

          FPR       TPR  threshold
0    0.000000  0.000000        inf
1    0.002681  0.000000     0.9985
2    0.002681  0.065574     0.9875
3    0.002681  0.081967     0.9855
4    0.002681  0.122951     0.9775
..        ...       ...        ...
145  0.662198  0.991803     0.0020
146  0.713137  0.991803     0.0015
147  0.766756  0.991803     0.0010
148  0.833780  0.991803     0.0005
149  1.000000  1.000000     0.0000

[150 rows x 3 columns]

Brazil demographics: fold 1/10, accuracy=0.70000, seconds=1.4

Brazil demographics: fold 2/10, accuracy=0.74000, seconds=1.4

Brazil demographics: fold 3/10, accuracy=0.76000, seconds=1.4

Brazil demographics: fold 4/10, accuracy=0.64000, seconds=1.4

Brazil demographics: fold 5/10, accuracy=0.80000, seconds=1.4

Brazil demographics: fold 6/10, accuracy=0.75510, seconds=1.4

Brazil demographics: fold 7/10, accuracy=0.77551, seconds=1.4

Brazil demographics: fold 8/10, accuracy=0.73469, seconds=1.4

Brazil demographics: fold 9/10, accuracy=0.71429, seconds=1.4

Brazil demographics: fold 10/10, accuracy=0.75510, seconds=1.4

,participant_id,target,fold,prediction,probability_right
0,e3428c81-c1a3-4139-9deb-ab2b9aae481d,0,8,0,0.085295
1,248860f8-a008-4207-84fd-a88cdc02e3f1,0,0,0,0.091500
2,f3d2061a-9ffa-4fc2-bf46-f9990b6055ec,0,0,1,0.670045
3,457cc0fc-957a-4984-a685-587b0686d18d,0,8,0,0.085295
4,fc8481a9-7975-43f3-8a76-c054d51e73ea,1,5,0,0.041326
...,...,...,...,...,...
490,33c490b5-f5e4-4db9-8d77-4f76fd0d363f,0,2,0,0.455235
491,5d5f537f-a895-49ed-966d-a5b31539155d,1,5,0,0.107390
492,035fef84-952f-40cf-b6bc-59419ebc4234,1,1,0,0.494081
493,730666d4-bf22-4c25-9df0-cd447cd72100,1,3,0,0.160431
494,464341cf-d0ec-4067-8905-a50b34a7fd90,1,2,0,0.011540

,fold,n_train,n_test,accuracy,recall_left,recall_right,auc,fit_seconds
0,0,445,50,0.700000,0.894737,0.083333,0.521930,1.381111
1,1,445,50,0.740000,0.947368,0.083333,0.491228,1.404592
2,2,445,50,0.760000,1.000000,0.000000,0.426535,1.367715
3,3,445,50,0.640000,0.864865,0.000000,0.602911,1.369445
4,4,445,50,0.800000,0.972973,0.307692,0.715177,1.388635
5,5,446,49,0.755102,0.945946,0.166667,0.574324,1.401160
6,6,446,49,0.775510,1.000000,0.083333,0.599099,1.374178
7,7,446,49,0.734694,0.972973,0.000000,0.425676,1.372763
8,8,446,49,0.714286,0.945946,0.000000,0.424550,1.395382
9,9,446,49,0.755102,0.972973,0.083333,0.549550,1.378856

   fold       age       sex    region
0     0  0.272886  0.057206  0.669908
1     1  0.268869  0.047422  0.683709
2     2  0.262051  0.054031  0.683918
3     3  0.293868  0.053320  0.652812
4     4  0.289021  0.056357  0.654621
5     5  0.289008  0.054010  0.656982
6     6  0.294869  0.052419  0.652712
7     7  0.298869  0.067641  0.633490
8     8  0.290259  0.053002  0.656738
9     9  0.297633  0.049617  0.652750

          FPR       TPR  threshold
0    0.000000  0.000000        inf
1    0.002681  0.000000   0.945619
2    0.005362  0.000000   0.934603
3    0.005362  0.016393   0.886253
4    0.016086  0.016393   0.858786
..        ...       ...        ...
170  0.959786  0.959016   0.000638
171  0.959786  0.967213   0.000583
172  0.962466  0.975410   0.000364
173  0.962466  0.983607   0.000278
174  1.000000  1.000000   0.000000

[175 rows x 3 columns]

Brazil combined: fold 1/10, accuracy=0.82000, seconds=1.4

Brazil combined: fold 2/10, accuracy=0.90000, seconds=1.4

Brazil combined: fold 3/10, accuracy=0.88000, seconds=1.4

Brazil combined: fold 4/10, accuracy=0.96000, seconds=1.4

Brazil combined: fold 5/10, accuracy=0.88000, seconds=1.4

Brazil combined: fold 6/10, accuracy=0.93878, seconds=1.4

Brazil combined: fold 7/10, accuracy=0.87755, seconds=1.4

Brazil combined: fold 8/10, accuracy=0.87755, seconds=1.4

Brazil combined: fold 9/10, accuracy=0.91837, seconds=1.4

Brazil combined: fold 10/10, accuracy=0.83673, seconds=1.4

,participant_id,target,fold,prediction,probability_right
0,e3428c81-c1a3-4139-9deb-ab2b9aae481d,0,8,0,0.0080
1,248860f8-a008-4207-84fd-a88cdc02e3f1,0,0,0,0.3175
2,f3d2061a-9ffa-4fc2-bf46-f9990b6055ec,0,0,0,0.0150
3,457cc0fc-957a-4984-a685-587b0686d18d,0,8,0,0.0670
4,fc8481a9-7975-43f3-8a76-c054d51e73ea,1,5,1,0.7850
...,...,...,...,...,...
490,33c490b5-f5e4-4db9-8d77-4f76fd0d363f,0,2,0,0.1765
491,5d5f537f-a895-49ed-966d-a5b31539155d,1,5,1,0.8365
492,035fef84-952f-40cf-b6bc-59419ebc4234,1,1,1,0.8140
493,730666d4-bf22-4c25-9df0-cd447cd72100,1,3,1,0.8250
494,464341cf-d0ec-4067-8905-a50b34a7fd90,1,2,1,0.5185

,fold,n_train,n_test,accuracy,recall_left,recall_right,auc,fit_seconds
0,0,445,50,0.820000,0.894737,0.583333,0.907895,1.405821
1,1,445,50,0.900000,0.921053,0.833333,0.916667,1.390412
2,2,445,50,0.880000,0.947368,0.666667,0.947368,1.384829
3,3,445,50,0.960000,0.945946,1.000000,0.970894,1.396739
4,4,445,50,0.880000,0.945946,0.692308,0.958420,1.350788
5,5,446,49,0.938776,0.945946,0.916667,0.988739,1.400528
6,6,446,49,0.877551,0.891892,0.833333,0.896396,1.391909
7,7,446,49,0.877551,0.891892,0.833333,0.954955,1.396537
8,8,446,49,0.918367,0.972973,0.750000,0.889640,1.388495
9,9,446,49,0.836735,0.864865,0.750000,0.934685,1.392246

   fold       age       sex    region        z1        z2
0     0  0.054644  0.021713  0.067302  0.697457  0.158884
1     1  0.054915  0.023995  0.072999  0.682314  0.165777
2     2  0.055687  0.023460  0.073501  0.684878  0.162474
3     3  0.056208  0.023184  0.071708  0.680896  0.168005
4     4  0.052850  0.022192  0.064660  0.700198  0.160100
5     5  0.057257  0.022814  0.067300  0.680865  0.171764
6     6  0.054390  0.021238  0.062296  0.699852  0.162222
7     7  0.055778  0.022459  0.069095  0.691258  0.161411
8     8  0.054711  0.023519  0.066805  0.700757  0.154208
9     9  0.056129  0.021892  0.072499  0.690270  0.159210

          FPR       TPR  threshold
0    0.000000  0.000000        inf
1    0.002681  0.000000     0.9890
2    0.002681  0.024590     0.9805
3    0.002681  0.040984     0.9795
4    0.002681  0.057377     0.9630
..        ...       ...        ...
154  0.863271  0.991803     0.0020
155  0.903485  0.991803     0.0015
156  0.932976  0.991803     0.0010
157  0.962466  1.000000     0.0005
158  1.000000  1.000000     0.0000

[159 rows x 3 columns]

Brazil pc1: fold 1/10, accuracy=0.86000, seconds=1.4

Brazil pc1: fold 2/10, accuracy=0.88000, seconds=1.4

Brazil pc1: fold 3/10, accuracy=0.84000, seconds=1.4

Brazil pc1: fold 4/10, accuracy=0.86000, seconds=1.4

Brazil pc1: fold 5/10, accuracy=0.82000, seconds=1.4

Brazil pc1: fold 6/10, accuracy=0.85714, seconds=1.4

Brazil pc1: fold 7/10, accuracy=0.87755, seconds=1.4

Brazil pc1: fold 8/10, accuracy=0.81633, seconds=1.4

Brazil pc1: fold 9/10, accuracy=0.75510, seconds=1.4

Brazil pc1: fold 10/10, accuracy=0.85714, seconds=1.4

,participant_id,target,fold,prediction,probability_right
0,e3428c81-c1a3-4139-9deb-ab2b9aae481d,0,8,0,0.0000
1,248860f8-a008-4207-84fd-a88cdc02e3f1,0,0,1,0.6430
2,f3d2061a-9ffa-4fc2-bf46-f9990b6055ec,0,0,0,0.0000
3,457cc0fc-957a-4984-a685-587b0686d18d,0,8,0,0.0000
4,fc8481a9-7975-43f3-8a76-c054d51e73ea,1,5,1,0.9990
...,...,...,...,...,...
490,33c490b5-f5e4-4db9-8d77-4f76fd0d363f,0,2,0,0.0355
491,5d5f537f-a895-49ed-966d-a5b31539155d,1,5,1,1.0000
492,035fef84-952f-40cf-b6bc-59419ebc4234,1,1,1,1.0000
493,730666d4-bf22-4c25-9df0-cd447cd72100,1,3,1,0.9950
494,464341cf-d0ec-4067-8905-a50b34a7fd90,1,2,0,0.3605

,fold,n_train,n_test,accuracy,recall_left,recall_right,auc,fit_seconds
0,0,445,50,0.860000,0.921053,0.666667,0.912281,1.377983
1,1,445,50,0.880000,0.921053,0.750000,0.911184,1.377110
2,2,445,50,0.840000,0.947368,0.500000,0.955044,1.381929
3,3,445,50,0.860000,0.918919,0.692308,0.956341,1.396351
4,4,445,50,0.820000,0.891892,0.615385,0.914761,1.413326
5,5,446,49,0.857143,0.891892,0.750000,0.951577,1.379276
6,6,446,49,0.877551,0.864865,0.916667,0.897523,1.383263
7,7,446,49,0.816327,0.864865,0.666667,0.911036,1.390964
8,8,446,49,0.755102,0.810811,0.583333,0.811937,1.411909
9,9,446,49,0.857143,0.918919,0.666667,0.925676,1.376712

   fold  PC1
0     0  1.0
1     1  1.0
2     2  1.0
3     3  1.0
4     4  1.0
5     5  1.0
6     6  1.0
7     7  1.0
8     8  1.0
9     9  1.0

         FPR       TPR  threshold
0   0.000000  0.000000        inf
1   0.008043  0.221311     1.0000
2   0.008043  0.245902     0.9995
3   0.010724  0.278689     0.9990
4   0.013405  0.295082     0.9985
..       ...       ...        ...
88  0.276139  0.942623     0.0030
89  0.278820  0.950820     0.0025
90  0.281501  0.950820     0.0015
91  0.292225  0.983607     0.0005
92  1.000000  1.000000     0.0000

[93 rows x 3 columns]

{'coordinates': {'features': ['z1', 'z2'],
  'fold_accuracy_min': 0.8163265306122449,
  'fold_accuracy_max': 0.9387755102040817,
  'fold_accuracy_mean': 0.8725714285714286,
  'oof_accuracy': 0.8727272727272727,
  'oof_recall_left': 0.9222520107238605,
  'oof_recall_right': 0.7213114754098361,
  'oof_auc': 0.9317672394849033,
  'confusion_counts_left_right': [[344, 29], [34, 88]],
  'confusion_row_normalized_left_right': [[0.9222520107238605,
    0.0777479892761394],
   [0.2786885245901639, 0.7213114754098361]],
  'mean_feature_importance': {'z1': 0.7639777377918814,
   'z2': 0.23602226220811867}},
 'demographics': {'features': ['age', 'sex', 'region'],
  'fold_accuracy_min': 0.64,
  'fold_accuracy_max': 0.8,
  'fold_accuracy_mean': 0.737469387755102,
  'oof_accuracy': 0.7373737373737373,
  'oof_recall_left': 0.9517426273458445,
  'oof_recall_right': 0.08196721311475409,
  'oof_auc': 0.5283039599173736,
  'confusion_counts_left_right': [[355, 18], [112, 10]],
  'confusion_row_normalized_left_right': [[0.9517426273458445,
    0.04825737265415549],
   [0.9180327868852459, 0.08196721311475409]],
  'mean_feature_importance': {'age': 0.28573333246585503,
   'sex': 0.0545025919190288,
   'region': 0.6597640756151162}},
 'combined': {'features': ['age', 'sex', 'region', 'z1', 'z2'],
  'fold_accuracy_min': 0.82,
  'fold_accuracy_max': 0.96,
  'fold_accuracy_mean': 0.8888979591836735,
  'oof_accuracy': 0.8888888888888888,
  'oof_recall_left': 0.9222520107238605,
  'oof_recall_right': 0.7868852459016393,
  'oof_auc': 0.9357667120819232,
  'confusion_counts_left_right': [[344, 29], [26, 96]],
  'confusion_row_normalized_left_right': [[0.9222520107238605,
    0.0777479892761394],
   [0.21311475409836064, 0.7868852459016393]],
  'mean_feature_importance': {'age': 0.055256915508806,
   'sex': 0.0226467076334254,
   'region': 0.06881644480937135,
   'z1': 0.6908744123487515,
   'z2': 0.16240551969964576}},
 'pc1': {'features': ['PC1'],
  'fold_accuracy_min': 0.7551020408163265,
  'fold_accuracy_max': 0.88,
  'fold_accuracy_mean': 0.8423265306122449,
  'oof_accuracy': 0.8424242424242424,
  'oof_recall_left': 0.8954423592493298,
  'oof_recall_right': 0.680327868852459,
  'oof_auc': 0.9185711774271526,
  'confusion_counts_left_right': [[334, 39], [39, 83]],
  'confusion_row_normalized_left_right': [[0.8954423592493298,
    0.10455764075067024],
   [0.319672131147541, 0.680327868852459]],
  'mean_feature_importance': {'PC1': 1.0}}}

,country,model,n,fold_accuracy_min,fold_accuracy_max,fold_accuracy_mean,oof_accuracy,oof_recall_left,oof_recall_right,oof_auc
0,Chile,coordinates,22024,0.790191,0.815622,0.803305,0.803305,0.837586,0.758628,0.867072
1,Chile,demographics,22024,0.545166,0.579210,0.561160,0.561161,0.715615,0.359862,0.567266
2,Chile,combined,22024,0.801090,0.831971,0.815519,0.815519,0.849703,0.770968,0.879207
3,Chile,pc1,22024,0.725828,0.755677,0.743871,0.743870,0.771225,0.708220,0.837743
4,France,coordinates,788,0.860759,0.949367,0.912496,0.912437,0.959627,0.701389,0.941808
5,France,demographics,788,0.810127,0.822785,0.817267,0.817259,1.000000,0.000000,0.542912
6,France,combined,788,0.860759,0.949367,0.911246,0.911168,0.961180,0.687500,0.945798
7,France,pc1,788,0.797468,0.949367,0.879552,0.879442,0.930124,0.652778,0.901953
8,Brazil,coordinates,495,0.816327,0.938776,0.872571,0.872727,0.922252,0.721311,0.931767
9,Brazil,demographics,495,0.640000,0.800000,0.737469,0.737374,0.951743,0.081967,0.528304
10,Brazil,combined,495,0.820000,0.960000,0.888898,0.888889,0.922252,0.786885,0.935767
11,Brazil,pc1,495,0.755102,0.880000,0.842327,0.842424,0.895442,0.680328,0.918571

## Describe validation at different observed participation levels

Merge the combined model's live out-of-fold predictions with each person's total retained comparison count. `qcut` forms country-specific groups by quantiles of that count. Ties stay together, so duplicate quantile edges can yield fewer than the requested ten groups. The reported minimum and maximum counts show what each group contains.

Every eligible participant must appear in exactly one group, and group error counts must sum to the overall error count. These are descriptive comparisons of existing histories. They do not truncate choice histories or estimate the causal effect of asking more questions.

In [4]:
activity_frames = []
for country in COUNTRIES:
    destination = OUT / country
    count_path = ROOT / COUNTS[country]
    counts = pd.read_csv(count_path, dtype={"uuid": str, "user_id": str})
    counts = counts.rename(
        columns={
            "uuid": "participant_id",
            "user_id": "participant_id",
            "total_choices": "observed_count",
            "n_choices": "observed_count",
        }
    )
    assert counts.participant_id.is_unique
    assert (counts.observed_count > 0).all()
    assert (counts.observed_count == counts.observed_count.astype(int)).all()
    prediction = combined_predictions[country].copy()
    prediction = prediction.merge(
        counts[["participant_id", "observed_count"]],
        on="participant_id",
        how="left",
        validate="one_to_one",
    )
    assert prediction.observed_count.notna().all()
    prediction["group"] = pd.qcut(
        prediction.observed_count, ACTIVITY_GROUPS, labels=False, duplicates="drop"
    )
    assert prediction.group.notna().all()
    prediction["group"] = prediction.group.astype(int) + 1
    rows = []
    for group, frame in prediction.groupby("group"):
        rows.append(
            {
                "country": country,
                "group": int(group),
                "n": len(frame),
                "n_left": int(frame.target.eq(0).sum()),
                "n_right": int(frame.target.eq(1).sum()),
                "count_min": int(frame.observed_count.min()),
                "count_median": float(frame.observed_count.median()),
                "count_max": int(frame.observed_count.max()),
                "accuracy": float(accuracy_score(frame.target, frame.prediction)),
                "recall_left": float(
                    recall_score(frame.target, frame.prediction, pos_label=0, zero_division=0)
                ),
                "recall_right": float(
                    recall_score(frame.target, frame.prediction, pos_label=1, zero_division=0)
                ),
                "error_count": int(frame.target.ne(frame.prediction).sum()),
            }
        )
    activity = pd.DataFrame(rows)
    assert activity.n.sum() == len(prediction)
    assert activity.error_count.sum() == prediction.target.ne(prediction.prediction).sum()
    assert np.allclose(activity.accuracy, 1 - activity.error_count / activity.n)
    display(prediction)
    prediction.to_csv(destination / "combined_oof_with_activity.csv", index=False)
    display(activity)
    activity.to_csv(destination / "activity_groups.csv", index=False)
    activity.to_latex(destination / "activity_groups.tex", index=False, float_format="%.6f")
    activity_frames.append(activity)

all_activity = pd.concat(activity_frames, ignore_index=True)
display(all_activity)
all_activity.to_csv(OUT / "activity_groups.csv", index=False)
all_activity.to_latex(OUT / "activity_groups.tex", index=False, float_format="%.6f")

,participant_id,target,fold,prediction,probability_right,observed_count,group
0,8bd42737-b140-4db8-af4c-59839922129a,0,8,1,0.8710,63,6
1,7d2e034a-3270-4429-aeac-418c46bf0d7d,1,0,1,0.8315,21,2
2,c1b97bb6-03d2-4027-8d54-0dd64a927a6c,0,4,1,0.6230,21,2
3,883528e9-0599-4d30-9f4c-1daf9cf74082,1,3,0,0.0280,91,8
4,7fd1210c-b1c0-4bdf-b190-7bfa10fe51d2,0,1,0,0.0850,60,6
...,...,...,...,...,...,...,...
22019,759b16f2-f527-4f04-85ba-682fd1af8a89,0,4,0,0.2845,91,8
22020,2e8f5550-d794-411c-b36e-d277e88f5d30,1,5,1,0.9930,114,9
22021,3ddc9eae-ba7b-4dab-8e43-5c188daf9692,0,0,1,0.5705,228,10
22022,b7132b2c-5ca4-44ac-b4e7-07e43d4b7547,1,4,1,0.7510,29,4
22023,1a38e668-bad8-41e5-9e24-050480272131,0,5,1,0.7015,50,6

,country,group,n,n_left,n_right,count_min,count_median,count_max,accuracy,recall_left,recall_right,error_count
0,Chile,1,2640,1258,1382,2,19.0,20,0.774242,0.795707,0.754703,596
1,Chile,2,3497,2161,1336,21,21.0,21,0.770947,0.826932,0.680389,801
2,Chile,3,647,385,262,22,22.0,23,0.788253,0.844156,0.706107,137
3,Chile,4,2076,1243,833,24,28.0,33,0.793353,0.839903,0.723890,429
4,Chile,5,2237,1378,859,34,40.0,47,0.820742,0.859942,0.757858,401
5,Chile,6,2145,1216,929,48,56.0,66,0.823776,0.851151,0.787944,378
6,Chile,7,2211,1242,969,67,79.0,85,0.838987,0.855072,0.818369,356
7,Chile,8,2178,1188,990,86,95.0,102,0.841598,0.881313,0.793939,345
8,Chile,9,2190,1220,970,103,118.0,145,0.851598,0.879508,0.816495,325
9,Chile,10,2203,1171,1032,146,200.0,764,0.866092,0.879590,0.850775,295

,participant_id,target,fold,prediction,probability_right,observed_count,group
0,e9001e65-7aa1-468d-a7c6-dca4ad023e59,0,9,0,0.0120,41,1
1,41e3bf3a-e792-4521-8d3a-8f974f329345,0,9,0,0.0000,3781,10
2,a664ff56-e303-4ab5-8841-bc950222e75f,0,9,0,0.0000,2911,9
3,7490cb32-18ba-4572-9310-c0c3801438d0,1,9,1,0.9810,2776,9
4,fecf3440-84f3-4bcb-b2c4-f6c939d80ec7,0,4,0,0.0050,2457,8
...,...,...,...,...,...,...,...
783,9026410e-9aa7-4bf8-aafa-8dbd26c94c63,1,1,1,0.6330,220,2
784,67e9a740-4137-4834-9331-a54929c5e6a9,0,1,0,0.0000,1720,5
785,48243d8e-ab20-4379-b9ba-ba76c4cde2f3,0,4,0,0.0635,1279,4
786,a7adb7e7-e526-49b9-93d5-563f75aa7714,0,6,0,0.0000,2101,6
787,23dc2d73-ff4b-4b6b-b4fb-35380d616e18,0,1,1,0.7175,19,1

,country,group,n,n_left,n_right,count_min,count_median,count_max,accuracy,recall_left,recall_right,error_count
0,France,1,79,61,18,14,41.0,81,0.835443,0.868852,0.722222,13
1,France,2,79,62,17,82,130.0,220,0.911392,0.983871,0.647059,7
2,France,3,79,62,17,223,369.0,577,0.886076,0.951613,0.647059,9
3,France,4,78,67,11,588,1055.5,1428,0.948718,1.000000,0.636364,4
4,France,5,79,70,9,1433,1645.0,1856,0.911392,0.971429,0.444444,7
5,France,6,80,69,11,1863,2038.0,2164,0.900000,0.942029,0.636364,8
6,France,7,77,62,15,2168,2332.0,2454,0.987013,1.000000,0.933333,1
7,France,8,79,66,13,2455,2574.0,2698,0.898734,0.969697,0.538462,8
8,France,9,79,60,19,2700,2808.0,3007,0.936709,0.966667,0.842105,5
9,France,10,79,65,14,3008,3263.0,3809,0.898734,0.953846,0.642857,8

,participant_id,target,fold,prediction,probability_right,observed_count,group
0,e3428c81-c1a3-4139-9deb-ab2b9aae481d,0,8,0,0.0080,20,2
1,248860f8-a008-4207-84fd-a88cdc02e3f1,0,0,0,0.3175,114,6
2,f3d2061a-9ffa-4fc2-bf46-f9990b6055ec,0,0,0,0.0150,25,3
3,457cc0fc-957a-4984-a685-587b0686d18d,0,8,0,0.0670,40,4
4,fc8481a9-7975-43f3-8a76-c054d51e73ea,1,5,1,0.7850,772,10
...,...,...,...,...,...,...,...
490,33c490b5-f5e4-4db9-8d77-4f76fd0d363f,0,2,0,0.1765,52,5
491,5d5f537f-a895-49ed-966d-a5b31539155d,1,5,1,0.8365,475,8
492,035fef84-952f-40cf-b6bc-59419ebc4234,1,1,1,0.8140,470,8
493,730666d4-bf22-4c25-9df0-cd447cd72100,1,3,1,0.8250,25,3
494,464341cf-d0ec-4067-8905-a50b34a7fd90,1,2,1,0.5185,12,1

,country,group,n,n_left,n_right,count_min,count_median,count_max,accuracy,recall_left,recall_right,error_count
0,Brazil,1,53,35,18,1,11.0,14,0.830189,0.885714,0.722222,9
1,Brazil,2,47,34,13,15,18.0,21,0.808511,0.823529,0.769231,9
2,Brazil,3,49,39,10,22,26.0,33,0.897959,0.974359,0.600000,5
3,Brazil,4,51,42,9,34,44.0,51,0.862745,0.904762,0.666667,7
4,Brazil,5,49,33,16,52,63.0,72,0.857143,0.878788,0.812500,7
5,Brazil,6,48,33,15,73,110.0,190,0.854167,0.939394,0.666667,7
6,Brazil,7,49,42,7,194,299.0,357,0.918367,0.928571,0.857143,4
7,Brazil,8,50,41,9,363,428.5,495,0.960000,0.951220,1.000000,2
8,Brazil,9,49,42,7,496,537.0,684,0.918367,0.928571,0.857143,4
9,Brazil,10,50,32,18,686,800.0,1192,0.980000,1.000000,0.944444,1

,country,group,n,n_left,n_right,count_min,count_median,count_max,accuracy,recall_left,recall_right,error_count
0,Chile,1,2640,1258,1382,2,19.0,20,0.774242,0.795707,0.754703,596
1,Chile,2,3497,2161,1336,21,21.0,21,0.770947,0.826932,0.680389,801
2,Chile,3,647,385,262,22,22.0,23,0.788253,0.844156,0.706107,137
3,Chile,4,2076,1243,833,24,28.0,33,0.793353,0.839903,0.723890,429
4,Chile,5,2237,1378,859,34,40.0,47,0.820742,0.859942,0.757858,401
5,Chile,6,2145,1216,929,48,56.0,66,0.823776,0.851151,0.787944,378
6,Chile,7,2211,1242,969,67,79.0,85,0.838987,0.855072,0.818369,356
7,Chile,8,2178,1188,990,86,95.0,102,0.841598,0.881313,0.793939,345
8,Chile,9,2190,1220,970,103,118.0,145,0.851598,0.879508,0.816495,325
9,Chile,10,2203,1171,1032,146,200.0,764,0.866092,0.879590,0.850775,295
10,France,1,79,61,18,14,41.0,81,0.835443,0.868852,0.722222,13
11,France,2,79,62,17,82,130.0,220,0.911392,0.983871,0.647059,7
12,France,3,79,62,17,223,369.0,577,0.886076,0.951613,0.647059,9
13,France,4,78,67,11,588,1055.5,1428,0.948718,1.000000,0.636364,4
14,France,5,79,70,9,1433,1645.0,1856,0.911392,0.971429,0.444444,7
15,France,6,80,69,11,1863,2038.0,2164,0.900000,0.942029,0.636364,8
16,France,7,77,62,15,2168,2332.0,2454,0.987013,1.000000,0.933333,1
17,France,8,79,66,13,2455,2574.0,2698,0.898734,0.969697,0.538462,8
18,France,9,79,60,19,2700,2808.0,3007,0.936709,0.966667,0.842105,5
19,France,10,79,65,14,3008,3263.0,3809,0.898734,0.953846,0.642857,8
20,Brazil,1,53,35,18,1,11.0,14,0.830189,0.885714,0.722222,9
21,Brazil,2,47,34,13,15,18.0,21,0.808511,0.823529,0.769231,9
22,Brazil,3,49,39,10,22,26.0,33,0.897959,0.974359,0.600000,5
23,Brazil,4,51,42,9,34,44.0,51,0.862745,0.904762,0.666667,7
24,Brazil,5,49,33,16,52,63.0,72,0.857143,0.878788,0.812500,7
25,Brazil,6,48,33,15,73,110.0,190,0.854167,0.939394,0.666667,7
26,Brazil,7,49,42,7,194,299.0,357,0.918367,0.928571,0.857143,4
27,Brazil,8,50,41,9,363,428.5,495,0.960000,0.951220,1.000000,2
28,Brazil,9,49,42,7,496,537.0,684,0.918367,0.928571,0.857143,4
29,Brazil,10,50,32,18,686,800.0,1192,0.980000,1.000000,0.944444,1